const app=document.getElementById('app'),screens=units[0].screens;
let question=0,revealed=false,seen=new Set();
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function textAt(screen,y){return screen.items.find(i=>i.type==='text'&&+i.a.y===y&&!i.tx&&!i.ty)?.text||'';}
function art(screen,label){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="70 230 250 190" role="img" aria-label="${esc(label)}">${screen.items.map(i=>`<g transform="translate(${i.tx||0} ${i.ty||0}) scale(${i.scale||1})"><${i.type} ${Object.entries(i.a).map(([k,v])=>`${k}="${esc(v)}"`).join(' ')}>${i.type==='text'?esc(i.text):''}</${i.type}></g>`).join('')}</svg>`;}
function home(){app.innerHTML=`<div class="intro"><p class="eyebrow">端午節 / Dragon Boat Festival</p><h1>翻張卡，一起認識端午節！</h1><p>日期、食物、活動與傳說，十個問題慢慢探索。</p><div class="intro-pictures">${[4,10,12].map(i=>`<div>${art(screens[i],'端午節插圖')}</div>`).join('')}</div><div class="route">① 看題目，想一想　→　② 翻卡看答案　→　③ 下一題</div><p>可以先和同學說說你的答案，再按「翻卡看答案」。</p><button class="primary" id="start">▶ ${seen.size?'重新開始':'開始探索'}</button><p class="english">10題 · 中英對照 · 不計分</p></div>`;window.scrollTo(0,0);}
function render(){const q=screens[question*2],a=screens[question*2+1];app.innerHTML=`<div class="lesson-heading"><button id="previous" ${question===0&&!revealed?'disabled':''}>← ${revealed?'回到題目':'上一題'}</button><strong>第 ${question+1} / 10 題</strong><span>已看答案 ${seen.size} / 10</span></div><div class="reading-progress" role="progressbar" aria-label="已看答案" aria-valuenow="${seen.size}" aria-valuemin="0" aria-valuemax="10"><span style="width:${seen.size*10}%"></span></div><article class="lesson"><p class="eyebrow">${revealed?'ANSWER / 答案':'QUESTION / 題目'}</p><h1 tabindex="-1" id="cardTitle">${esc(textAt(q,149))}</h1><p class="english">${esc(textAt(q,183))}</p><div class="card-art">${art(revealed?a:q,revealed?'答案插圖':'題目提示插圖')}</div>${revealed?`<div class="answer-copy"><h2>${esc(textAt(a,468))}</h2><p lang="en">${esc(textAt(a,507))}</p><p>${esc(textAt(a,560))}</p><p class="english" lang="en">${esc(textAt(a,595))}</p></div><button class="primary" id="next">${question===9?'完成，再玩一次 ↻':'下一題 →'}</button>${question===9?'<p class="finished" role="status">你已走到第10題！可以再玩一次，或回首頁。</p><button id="finishHome">⌂ 回首頁</button>':''}`:`<p>先想一想，再翻卡。</p><p class="english">Think first, then reveal.</p><button class="primary" id="reveal">↻ 翻卡看答案</button>`}<p class="footnote">知識探索不計分 · Learn at your own pace</p></article>`;window.scrollTo(0,0);document.getElementById('cardTitle').focus({preventScroll:true});}
document.getElementById('home').onclick=home;
app.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='start'){question=0;revealed=false;seen.clear();render();}else if(b.id==='reveal'){revealed=true;seen.add(question);render();}else if(b.id==='next'){if(question===9){question=0;seen.clear();}else question++;revealed=false;render();}else if(b.id==='previous'){if(revealed)revealed=false;else if(question>0){question--;revealed=true;}render();}else if(b.id==='finishHome')home();};
home();
