const labels=['家人團聚','送禮物','送卡片','出去玩','情人約會','謝謝老師','送花','吃湯圓','吃潤餅','吃粽子','吃月餅','貼春聯','發紅包','看花燈','猜燈謎','划龍舟','戴香包','賞月','掃墓','祭拜祖先','準備供品','拜好兄弟','祈求平安','冬至進補'];
const english=['Family gathering','Give a gift','Give a card','Go out and play','Go on a date','Thank a teacher','Give flowers','Eat tangyuan','Eat runbing','Eat zongzi','Eat mooncakes','Put up spring couplets','Give red envelopes','Enjoy lanterns','Solve lantern riddles','Paddle a dragon boat','Wear a sachet','Admire the moon','Tend family graves','Honor ancestors','Prepare offerings','Make Zhongyuan offerings','Pray for peace','Winter nourishing stew'];
const colors=['#df6b29','#dba817','#348553','#8554a1'];
const cards=labels.map((name,i)=>({id:i+1,name,en:english[i],color:colors[i===23?1:i<7?0:i<11?1:i<18?2:3]}));
const $=id=>document.getElementById(id);
let db,recordings=new Map(),activeAudio=null,audioURL=null,recorder=null,stream=null,recTimer=null,recordingCard=null,recordOpening=false,toastTimer;
let gameFestival=0;const dealBadges=new Set();
let playing=false,targets=[],collected=new Set(),order=[...cards],round=0;
const spriteX=[20,210,400,589,779,970,1161,1351],spriteY=[110,383,653],spriteH=[207,204,218];
function art(c){if(c.id===24)return `<span class="art" role="img" aria-label="冬至進補"><img src="winter-stew.png" alt="" draggable="false" style="width:100%;height:100%;object-fit:cover;left:0;top:0"></span>`;const i=c.id-1,row=Math.floor(i/8),x=spriteX[i%8],y=spriteY[row],w=174,h=spriteH[row];return `<span class="art" role="img" aria-label="${c.name}"><img src="activities.png" alt="" draggable="false" style="width:${1542/w*100}%;height:${1020/h*100}%;left:${-x/w*100}%;top:${-y/h*100}%"></span>`;}
function toast(t){$('status').textContent=t;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('status').textContent='',5000);}
function stopAudio(){if(activeAudio){activeAudio.pause();activeAudio=null;}if(audioURL){URL.revokeObjectURL(audioURL);audioURL=null;}if('speechSynthesis'in window)speechSynthesis.cancel();}
async function speak(c){stopAudio();const blob=recordings.get(c.id);if(blob){audioURL=URL.createObjectURL(blob);activeAudio=new Audio(audioURL);try{await activeAudio.play();return true;}catch{toast('錄音無法播放，請重新錄製。');return false;}}if(!('speechSynthesis'in window)){toast('這個瀏覽器無法示範朗讀。請先錄音，或使用文字提示。');return false;}const utter=new SpeechSynthesisUtterance(c.name);utter.lang='zh-TW';utter.rate=.8;const voices=speechSynthesis.getVoices();utter.voice=voices.find(v=>v.lang==='zh-TW')||voices.find(v=>v.lang.startsWith('zh'))||null;utter.onerror=e=>{if(!['interrupted','canceled'].includes(e.error))toast('示範朗讀不可用，請先錄音，或使用文字提示。');};speechSynthesis.speak(utter);return true;}
function renderLibrary(){const library=$('library');library.innerHTML=cards.map(c=>`<article class="activity" data-activity="${c.id}" style="--category:${c.color}"><button class="picture-button" data-listen="${c.id}" aria-label="聽${c.name}">${art(c)}<span class="category-mark"></span><span class="card-copy"><strong>${c.name}</strong><small lang="en">${c.en}</small></span></button><button class="related-button" data-related="${c.id}">看相關節日 →</button><button class="record-button ${recordings.has(c.id)?'saved':''}" data-record="${c.id}">${recordings.has(c.id)?'✓ 已錄音・重錄':'🎙 錄音'}</button></article>`).join('');$('recordCount').textContent=`已錄音 ${recordings.size} / 24`;}
$('library').addEventListener('click',e=>{const listen=e.target.closest('[data-listen]'),record=e.target.closest('[data-record]');if(listen)speak(cards[+listen.dataset.listen-1]);if(record)openRecord(+record.dataset.record);});
function openRecord(id){stopAudio();recordingCard=cards[id-1];$('recTitle').textContent=recordingCard.name;$('recEnglish').textContent=recordingCard.en;$('recStatus').textContent=recordings.has(id)?'這張卡已有錄音，可試聽或重錄。':'每次最多 20 秒。';$('recStatus').className='';$('record').disabled=!db;$('stopRecord').disabled=true;$('listenRecord').disabled=!recordings.has(id);$('recDialog').showModal();}
function releaseMic(){clearTimeout(recTimer);if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}}
function closeRecord(){if(recordOpening||(recorder&&recorder.state==='recording')){toast('請先按「停止並儲存」。');return;}$('recDialog').close();stopAudio();}
$('closeRec').onclick=closeRecord;$('recDialog').addEventListener('cancel',e=>{e.preventDefault();closeRecord();});
$('record').onclick=async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){$('recStatus').textContent='錄音需要支援麥克風的瀏覽器，請用 Chrome／Edge 開啟 localhost 或 HTTPS 網址。';return;}recordOpening=true;$('record').disabled=true;stopAudio();$('recStatus').textContent='請允許使用麥克風…';try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(m=>MediaRecorder.isTypeSupported(m));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const id=recordingCard.id,chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=async()=>{releaseMic();$('stopRecord').disabled=true;$('recStatus').textContent='正在儲存…';const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});try{if(!blob.size)throw Error('empty');await saveRecording(id,blob);recordings.set(id,blob);renderLibrary();$('recStatus').textContent='✓ 已儲存，點圖片就能聽見你的聲音。';$('listenRecord').disabled=false;}catch{$('recStatus').textContent='未能儲存錄音，請檢查瀏覽器儲存空間後重試。';}$('recStatus').className='';$('record').disabled=false;};recorder.onerror=()=>{releaseMic();$('recStatus').textContent='錄音中斷，請重新錄音。';$('record').disabled=false;$('stopRecord').disabled=true;};recorder.start();$('stopRecord').disabled=false;$('listenRecord').disabled=true;$('recStatus').className='recording';$('recStatus').textContent='● 錄音中…說完後按「停止並儲存」（最多 20 秒）。';recTimer=setTimeout(()=>{if(recorder.state==='recording')recorder.stop();},20000);}catch(e){releaseMic();$('record').disabled=false;$('recStatus').textContent=e.name==='NotAllowedError'?'未取得麥克風權限。請在網址列允許麥克風，再試一次。':'找不到可用的麥克風，請檢查裝置後重試。';}finally{recordOpening=false;}};
$('stopRecord').onclick=()=>{if(recorder?.state==='recording'){recorder.stop();$('stopRecord').disabled=true;}};
$('listenRecord').onclick=()=>speak(recordingCard);
function saveRecording(id,blob){return new Promise((resolve,reject)=>{const tx=db.transaction('recordings','readwrite');tx.objectStore('recordings').put({id,blob});tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function initRecordings(){return new Promise(resolve=>{try{const req=indexedDB.open('festival-voice-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('recordings',{keyPath:'id'});req.onerror=()=>{toast('此瀏覽器無法保存錄音；仍可用示範朗讀試玩。');resolve();};req.onsuccess=()=>{db=req.result;const get=db.transaction('recordings').objectStore('recordings').getAll();get.onsuccess=()=>{recordings=new Map(get.result.map(r=>[r.id,r.blob]));renderLibrary();resolve();};get.onerror=()=>resolve();};}catch{toast('此瀏覽器無法保存錄音；仍可用示範朗讀試玩。');resolve();}});}
function setView(game){if(window.showPage){showPage(game?'gameView':'entryView');return;}stopAudio();$('learnView').hidden=game;$('gameView').hidden=!game;$('learnTab').classList.toggle('active',!game);$('gameTab').classList.toggle('active',game);$('learnTab').setAttribute('aria-pressed',String(!game));$('gameTab').setAttribute('aria-pressed',String(game));window.scrollTo({top:0,behavior:'smooth'});}
$('learnTab').onclick=()=>setView(false);$('gameTab').onclick=()=>setView(true);$('goGame').onclick=()=>setView(true);
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function renderBoard(){const words=$('showWords').checked;$('board').classList.toggle('words',words);$('board').innerHTML=order.map(c=>`<button class="game-card ${collected.has(c.id)?'collected':''}" style="--category:${c.color}" data-card="${c.id}" aria-label="${c.name}${collected.has(c.id)?'，已收集':''}" ${collected.has(c.id)?'disabled':''}>${art(c)}<span class="word">${c.name}</span></button>`).join('');}
function currentCard(){return cards[targets[collected.size]-1];}
function updateScore(){$('points').textContent=`${collected.size} 點`;$('progress').textContent=`已收集 ${collected.size} / 3`;$('slots').innerHTML=[0,1,2].map(i=>{const id=[...collected][i];return id?`<span class="filled">✓<br>${cards[id-1].name}</span>`:`<span>${i+1}</span>`;}).join('');}
function playPrompt(){if(!playing)return;const c=currentCard();$('prompt').textContent=`第 ${collected.size+1} 題：聽聲音，找出朋友想做的活動。${recordings.has(c.id)?'（學生錄音）':'（示範朗讀）'}`;speak(c);}
$('startGame').onclick=()=>{round++;stopAudio();playing=true;targets=shuffle(festivals[gameFestival].ids);collected=new Set();order=shuffle(cards);$('stamp').classList.remove('earned');$('stamp').innerHTML=`<span>${festivals[gameFestival].name[0]}</span><small>集滿三張蓋章</small>`;$('startGame').textContent='↻ 重新挑戰';$('replay').disabled=false;$('hint').disabled=false;updateScore();renderBoard();playPrompt();};
$('replay').onclick=playPrompt;$('hint').onclick=()=>{if(playing)$('prompt').textContent=`請找：${currentCard().name} / ${currentCard().en}`;};
$('shuffle').onclick=()=>{order=shuffle(order);renderBoard();toast('已洗牌，已收集的卡仍保留。');};$('showWords').onchange=renderBoard;
$('board').onclick=e=>{const button=e.target.closest('[data-card]');if(!button)return;if(!playing){toast(collected.size===3?`你已獲得${festivals[gameFestival].name}章！可以按「重新挑戰」。`:'先按「開始挑戰」，再聽提示。');return;}const id=+button.dataset.card;if(collected.has(id))return;if(id!==currentCard().id){button.classList.add('wrong');setTimeout(()=>button.classList.remove('wrong'),350);toast('再聽一次，找出這次提示的圖片。');return;}stopAudio();collected.add(id);updateScore();renderBoard();if(collected.size===3){playing=false;$('replay').disabled=true;$('hint').disabled=true;$('stamp').classList.add('earned');dealBadges.add(gameFestival);saveProgress();$('stamp').innerHTML=`<span>${festivals[gameFestival].name[0]}</span><small>${festivals[gameFestival].name} · 完成</small>`;$('prompt').textContent=`集滿三張！你完成了${festivals[gameFestival].name}挑戰，獲得一枚節日章。`;toast(`🎉 3 / 3！獲得${festivals[gameFestival].name}章！`);}else{toast('✓ 答對了！收集一張，+1 點。');const thisRound=round;setTimeout(()=>{if(playing&&thisRound===round&&!$('gameView').hidden)playPrompt();},700);}};
window.addEventListener('pagehide',()=>{stopAudio();releaseMic();});
renderLibrary();renderBoard();initRecordings();


