// 三種遊戲沿用 cards 的固定編號、圖片與 festivals 的節日對應。
const situations=[
 '過年了，大家回家，一起吃飯。','朋友過節，我準備一份小禮物送給他。','我想把祝福寫在一張卡片上，送給朋友。','兒童節到了，我們一起去公園玩。','七夕到了，我和喜歡的人一起吃晚餐。','老師幫助我學中文，我想對老師說謝謝。','我選了一束漂亮的花，送給重要的人。',
 '冬至到了，桌上有一碗圓圓的甜湯，大家一起吃。','清明節到了，我們把蔬菜包在薄薄的餅皮裡吃。','端午節到了，我們打開葉子，吃裡面的糯米。','中秋節到了，大家分著吃圓圓的月餅。','過年了，門口要貼上紅色的紙，上面有祝福的字。','過年了，長輩把錢放進紅色的袋子，送給小朋友。','元宵節晚上，大家去看亮亮的燈，有兔子，也有龍。','花燈下面有一道題目，大家一起想答案。','端午節，河上有長長的船，大家一起划，向前比賽。','端午節，我把一個有香味的小袋子掛在身上。','中秋節晚上，我們抬頭看又圓又亮的月亮。','清明節，我們去家人的墓前，清除雜草，整理環境。','我們在祖先的牌位前祭拜，表達思念與感謝。','祭拜前，我們把水果和食物放好。','中元節，我們準備食物，祭拜「好兄弟」。','我們合起雙手，希望大家都平安。','冬至天氣冷，家人煮了一鍋熱熱的雞湯，大家一起吃。'
];
const activityPhrases=cards.map(c=>c.id===1?'和家人團聚':c.id===24?'吃進補料理':c.name);
const gameBadges={2:new Set(),3:new Set()};
let practiceMode=2,practiceFestival=0,practiceIds=[],practiceStep=0,practiceCorrect=0,practicePhase='idle',selectedTokens=[],puzzleTokens=[];
const menu=document.createElement('section');menu.id='gamesMenu';menu.hidden=true;
menu.innerHTML=`<p class="eyebrow">B 遊戲式學習</p><h1>今天，想從哪個遊戲開始？</h1><p class="entry-intro">選一種玩法，跟著圖片與提示，一步一步完成挑戰。</p><div class="entry-options game-entry-options">
<article class="entry-option festival-entry"><div class="entry-label"><span>01</span><p>發牌遊戲<small lang="en">Listen and collect</small></p></div><h2>聽一聽，找圖卡</h2><p>聽活動名稱，找到圖片，集滿三張蓋章。</p><div class="route-example game-route"><strong>聽聲音</strong><span>↓ 找到對應圖片</span><div class="example-cards">${[1,12,13].map(id=>'<div style="--category:'+cards[id-1].color+'">'+art(cards[id-1])+'<strong>'+cards[id-1].name+'</strong></div>').join('')}</div></div><div class="entry-footer"><span>示範：春節 · 集滿 3 張獲得章</span><button class="primary" data-open-game="1">▶ 進入挑戰</button></div></article>
<article class="entry-option activity-entry"><div class="entry-label"><span>02</span><p>情境挑戰<small lang="en">Read and choose</small></p></div><h2>這是在做什麼？</h2><p>先記圖片，再讀或聽情境，選出適合的活動。</p><div class="route-example game-route"><strong>過年了，大家回家，一起吃飯。</strong><span>↓ 選出適合的活動</span><div class="example-cards single-example"><div style="--category:${cards[0].color}">${art(cards[0])}<strong>家人團聚</strong></div></div></div><div class="entry-footer"><span>示範：選出適當情境</span><button class="activity-primary" data-open-game="2">▶ 進入挑戰</button></div></article>
<article class="entry-option festival-entry"><div class="entry-label"><span>03</span><p>句子重組<small lang="en">Arrange and say</small></p></div><h2>排一排，說句子</h2><p>把圖片與短詞排成句子，再聽一次、說一次。</p><div class="route-example game-route"><strong>會 ／ 吃湯圓 ／ 我們 ／ 在冬至</strong><span>↓ 排出完整句子</span><div class="sentence-preview">我們 <span>在冬至</span> 會 ${art(cards[7])}</div></div><div class="entry-footer"><span>示範：句子重組</span><button class="primary" data-open-game="3">▶ 進入挑戰</button></div></article></div>`;
$('recordsView').before(menu);
const practice=document.createElement('section');practice.id='practiceView';practice.hidden=true;
practice.innerHTML=`<button class="back-games">← B 遊戲選單</button><p class="eyebrow" id="practiceLabel"></p><h1 id="practiceTitle"></h1><label class="festival-select">選擇節日 <select id="practiceFestival">${festivals.map((f,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} ${f.name}</option>`).join('')}</select></label><div class="practice-panel"><div class="practice-top"><h2 id="practiceHeading"></h2><span id="practiceProgress"></span></div><div id="practiceContent"></div><p id="practiceFeedback" role="status" aria-live="polite"></p></div>`;
menu.after(practice);
$('gameView').insertAdjacentHTML('afterbegin','<button class="back-games">← B 遊戲選單</button><p class="eyebrow">B 遊戲式學習</p><h1>01 發牌遊戲</h1><p class="entry-intro">聽一聽，找圖卡 · 集滿三張，獲得節日章。</p>');
const originalShowPage=showPage;
showPage=function(id){clearTimeout(toastTimer);document.getElementById('status').textContent='';originalShowPage(id);menu.hidden=id!=='gamesMenu';practice.hidden=id!=='practiceView';if(['gamesMenu','practiceView'].includes(id)){['learnTab','gameTab','recordsTab'].forEach(x=>{$(x).classList.toggle('active',x==='gameTab');$(x).setAttribute('aria-pressed',String(x==='gameTab'));});}};
$('gameTab').onclick=()=>showPage('gamesMenu');
$('goGame').textContent='選一個遊戲 →';$('goGame').onclick=()=>showPage('gamesMenu');
document.querySelectorAll('.back-games').forEach(b=>b.onclick=()=>showPage('gamesMenu'));
menu.onclick=e=>{const b=e.target.closest('[data-open-game]');if(!b)return;if(b.dataset.openGame==='1'){showPage('gameView');return;}practiceMode=+b.dataset.openGame;practiceFestival=practiceMode===3?9:0;$('practiceFestival').value=practiceFestival;startPractice();showPage('practiceView');};
$('practiceFestival').onchange=()=>{practiceFestival=+$('practiceFestival').value;startPractice();};
function startPractice(){stopAudio();practiceIds=[...festivals[practiceFestival].ids];if(practiceMode===3&&practiceFestival===9)practiceIds=[8,1,24];practiceStep=0;practiceCorrect=0;$('practiceLabel').textContent=`B－0${practiceMode} · ${practiceMode===2?'記憶與理解':'回想與複習'}`;$('practiceTitle').textContent=practiceMode===2?'02 情境挑戰':'03 句子重組';renderPractice();}
function renderPractice(){stopAudio();$('practiceFeedback').textContent='';$('practiceProgress').textContent=`第 ${practiceStep+1} / 3 題`;
 if(practiceStep===3){practicePhase='complete';gameBadges[practiceMode].add(practiceFestival);saveProgress();$('practiceHeading').textContent='完成了！';$('practiceProgress').textContent='3 / 3';$('practiceContent').innerHTML=`<div class="completion-badge">${festivals[practiceFestival].name}<br><strong>${practiceMode===2?'情境理解章':'句子重組章'}</strong></div><p>你完成了 3 題！${practiceMode===2?`第一次選對 ${practiceCorrect} 題；其他題目也已練習完成。`:'再讀一次句子，把活動介紹給同學吧。'}</p><button id="restartPractice">再玩一次</button> <button class="finish-menu">回遊戲選單</button>`;$('restartPractice').onclick=startPractice;document.querySelector('.finish-menu').onclick=()=>showPage('gamesMenu');return;}
 const id=practiceIds[practiceStep],c=cards[id-1];
 if(practiceMode===2){practicePhase='memory';$('practiceHeading').textContent='先看圖，記住三個活動';const options=shuffle([c,...shuffle(cards.filter(x=>x.id!==id)).slice(0,2)]);$('practiceContent').innerHTML=`<p>點圖片可以聽活動名稱。準備好後，再讀情境。</p><div class="choice-grid">${options.map(v=>`<button class="choice" data-preview="${v.id}" style="--category:${v.color}">${art(v)}<strong>${v.name}</strong></button>`).join('')}</div><button id="readySituation" class="primary">我記好了 →</button>`;document.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>speak(cards[+b.dataset.preview-1]));$('readySituation').onclick=()=>showSituation(id,options);
 }else{practicePhase='puzzle';$('practiceHeading').textContent='把圖片與短詞排成兩句話';selectedTokens=[];puzzleTokens=[{text:'這是'},{text:c.name,image:id},{text:'。'},{text:'我們'},{text:`在${festivals[practiceFestival].name}`},{text:'會'},{text:activityPhrases[id-1],image:id},{text:'。'}];$('practiceContent').innerHTML=`<p>先排「這是……。」再排「我們在……會……。」<br>點下方詞卡加入句子；點上方詞卡可以放回。</p><div id="sentenceAnswer" class="token-row answer-row" aria-label="我的句子"></div><div id="sentencePool" class="token-row" aria-label="可選詞卡"></div><div class="game-actions"><button id="checkSentence" class="primary">檢查句子</button><button id="resetSentence">重新排列</button></div><div id="sentenceResult"></div>`;const order=shuffle(puzzleTokens.map((_,i)=>i));function renderTokens(){$('sentenceAnswer').innerHTML=selectedTokens.length?selectedTokens.map(i=>tokenHTML(i,'return')).join(''):'<span class="empty-answer">你的句子會出現在這裡……</span>';$('sentencePool').innerHTML=order.filter(i=>!selectedTokens.includes(i)).map(i=>tokenHTML(i,'add')).join('');document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{if(practicePhase!=='puzzle')return;const i=+b.dataset.token;if(b.dataset.action==='add')selectedTokens.push(i);else selectedTokens=selectedTokens.filter(v=>v!==i);$('practiceFeedback').textContent='';renderTokens();});}
 $('resetSentence').onclick=()=>{selectedTokens=[];$('practiceFeedback').textContent='';renderTokens();};$('checkSentence').onclick=()=>{if(selectedTokens.length!==puzzleTokens.length){$('practiceFeedback').textContent='還有詞卡沒放進句子，繼續試試看。';return;}if(selectedTokens.map(i=>puzzleTokens[i].text).join('')!==puzzleTokens.map(t=>t.text).join('')){$('practiceFeedback').textContent='再想想：先介紹活動，再說我們在什麼節日會做。點詞卡可放回重排。';return;}practicePhase='answered';$('practiceFeedback').textContent='✓ 排對了！聽一聽，再自己說一次。';$('checkSentence').disabled=true;$('resetSentence').disabled=true;document.querySelectorAll('[data-token]').forEach(b=>b.disabled=true);$('sentenceResult').innerHTML=`<p class="full-sentence">${puzzleTokens.map(t=>t.text).join('')}</p><button id="readSentence">🔊 聽完整句子</button> <button id="nextPractice" class="primary">${practiceStep===2?'領取完成章':'下一題 →'}</button>`;$('readSentence').onclick=()=>speak({name:puzzleTokens.map(t=>t.text).join('')});$('nextPractice').onclick=nextPractice;};renderTokens();}
}
function tokenHTML(i,action){const t=puzzleTokens[i];return `<button class="word-token ${t.image?'image-token':''}" data-token="${i}" data-action="${action}" aria-label="${action==='add'?'加入':'放回'}${t.text}">${t.image?art(cards[t.image-1]):''}<span>${t.text}</span></button>`;}
function showSituation(id,options){stopAudio();const situation=id===1&&practiceFestival!==0?`${festivals[practiceFestival].name}到了，大家回家，一起吃飯。`:id===8?`${festivals[practiceFestival].name}到了，桌上有一碗圓圓的甜湯，大家一起吃。`:situations[id-1];practicePhase='situation';$('practiceHeading').textContent='這是在做什麼？';$('practiceContent').innerHTML=`<p class="situation-text">${situation}</p><button id="readSituation">🔊 聽情境</button> <button id="showSituationChoices" class="primary">我想好了，選圖片 →</button><div id="situationChoices"></div>`;$('readSituation').onclick=()=>speak({name:situation});$('showSituationChoices').onclick=()=>{practicePhase='choosing';$('showSituationChoices').hidden=true;$('situationChoices').innerHTML=`<div class="choice-grid">${shuffle(options).map(c=>`<button class="choice" data-answer="${c.id}" aria-label="${c.name}" style="--category:${c.color}">${art(c)}</button>`).join('')}</div>`;let firstTry=true;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(practicePhase!=='choosing')return;if(+b.dataset.answer!==id){firstTry=false;$('practiceFeedback').textContent='再讀一次情境，試試另一張圖片。';return;}if(firstTry)practiceCorrect++;practicePhase='answered';$('practiceFeedback').textContent=`✓ ${cards[id-1].name}！你把情境和圖片連起來了。`;document.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);b.classList.add('correct-choice');$('situationChoices').insertAdjacentHTML('beforeend',`<button id="nextPractice" class="primary">${practiceStep===2?'領取完成章':'下一題 →'}</button>`);$('nextPractice').onclick=nextPractice;});};}
function nextPractice(){practiceStep++;renderPractice();}
const originalRenderRecords=renderRecords;
renderRecords=function(){originalRenderRecords();[2,3].forEach(mode=>{$('recordSummary').insertAdjacentHTML('beforeend',`<article><span>${mode===2?'02 情境理解':'03 句子重組'}</span><strong>${gameBadges[mode].size} 枚章</strong><p>${gameBadges[mode].size?[...gameBadges[mode]].map(i=>festivals[i].name).join('、'):'完成一個節日的 3 題，就能領章。'}</p><button data-record-game="${mode}">繼續練習 →</button></article>`);});document.querySelectorAll('[data-record-game]').forEach(b=>b.onclick=()=>{practiceMode=+b.dataset.recordGame;startPractice();showPage('practiceView');});};

function chooseDealFestival(index){gameFestival=index;round++;stopAudio();playing=false;targets=[];collected=new Set();order=shuffle(cards);const f=festivals[index];document.querySelector('.festival-strip').innerHTML=festivals.map((v,i)=>`<button data-deal-festival="${i}" class="${i===index?'current':''}" aria-pressed="${i===index}">${String(i+1).padStart(2,'0')} ${v.name}</button>`).join('');document.querySelector('.strip-note').textContent='選一個節日，再按「開始挑戰」。切換節日會重新開始，已獲得的章保留在本次學習記錄。';document.querySelector('.scenario .eyebrow').textContent=f.name+' / '+f.en;document.querySelector('.scenario h1').textContent='認識'+f.name+'的活動！';document.querySelector('.scenario h1+p').textContent='聽聽活動名稱，從24張圖卡找出本回合指定的三項活動，集滿就蓋章。';document.querySelector('.passport-top strong').textContent='我的'+f.name+'集點卡';document.querySelector('.game-rule').textContent='每張正確圖卡得1點；重複點選不加分。其他卡只是本回合目標不同，不代表不能用於這個節日。';$('stamp').classList.remove('earned');$('stamp').innerHTML=`<span>${f.name[0]}</span><small>集滿三張蓋章</small>`;$('startGame').textContent='▶ 開始挑戰';$('replay').disabled=true;$('hint').disabled=true;$('prompt').textContent='準備好了嗎？先按「開始挑戰」。';updateScore();renderBoard();}
document.querySelector('.festival-strip').onclick=e=>{const b=e.target.closest('[data-deal-festival]');if(b)chooseDealFestival(+b.dataset.dealFestival);};chooseDealFestival(0);
