const memoryBadges=new Set();
let memoryWaiting=false,memoryShuffling=false,memoryShuffleTimer;
let memoryFestival=0,memoryDeck=[],memoryMatched=new Set(),memoryAttempts=0,memoryRevealed=false;let memoryFlipped=new Set();
document.querySelector('.game-entry-options').insertAdjacentHTML('beforeend',`<article class="entry-option activity-entry"><div class="entry-label"><span>04</span><p>翻牌記憶<small>Memory match</small></p></div><h2>翻一翻，圖片配文字</h2><p>翻牌配對得1點，再蓋牌洗牌，挑戰下一組。</p><div class="route-example game-route"><strong>碗裡有圓圓的小糰子，大家用湯匙吃。</strong><span>↓ 選圖片，找對應文字</span><div class="memory-example"><div>${art(cards[7])}</div><span>↔</span><strong>吃湯圓</strong></div></div><div class="entry-footer"><span>示範：三張圖片＋三張文字</span><button class="activity-primary" data-open-game="4">▶ 進入挑戰</button></div></article>`);
const memoryView=document.createElement('section');memoryView.id='memoryView';memoryView.hidden=true;
memoryView.innerHTML=`<button id="memoryBack">← B 遊戲選單</button><p class="eyebrow">B 遊戲式學習</p><h1>04 翻牌記憶</h1><p>逐張翻開六張牌，配對一組得1點。按「蓋牌並洗牌」後重新翻牌，找下一組；三組都完成就獲得章。</p><label class="festival-select">選擇節日 <select id="memoryFestival">${festivals.map((f,i)=>`<option value="${i}">${String(i+1).padStart(2,'0')} ${f.name}</option>`).join('')}</select></label><div class="practice-panel"><div class="practice-top"><h2 id="memoryHeading"></h2><span id="memoryScore"></span></div><p id="memoryQuestion" class="situation-text"></p><button id="memoryListen">🔊 聽活動名稱</button><p id="memoryAttempts"></p><div id="memoryBoard" class="memory-board" aria-label="六張活動圖片"></div><p id="memoryFeedback" role="status" aria-live="polite"></p><div class="game-actions"><button id="memoryNext" class="primary" hidden>↻ 蓋牌並洗牌</button><button id="memoryRestart">↻ 換一組挑戰</button></div><div id="memoryAward"></div></div>`;
$('recordsView').before(memoryView);
const showBeforeMemory=showPage;
showPage=function(id){showBeforeMemory(id);memoryView.hidden=id!=='memoryView';if(id==='memoryView'){['learnTab','gameTab','recordsTab'].forEach(x=>{$(x).classList.toggle('active',x==='gameTab');$(x).setAttribute('aria-pressed',String(x==='gameTab'));});}};
const menuBeforeMemory=menu.onclick;
menu.onclick=e=>{const b=e.target.closest('[data-open-game]');if(b?.dataset.openGame==='4'){if(!memoryDeck.length)startMemory();showPage('memoryView');}else menuBeforeMemory(e);};
$('memoryBack').onclick=()=>showPage('gamesMenu');
$('memoryFestival').onchange=()=>{memoryFestival=+$('memoryFestival').value;startMemory();};
$('memoryRestart').onclick=startMemory;

function startMemory(){clearTimeout(memoryShuffleTimer);memoryWaiting=false;memoryShuffling=false;stopAudio();memoryDeck=shuffle(festivals[memoryFestival].ids.flatMap(id=>[{id,kind:'picture'},{id,kind:'word'}]));memoryFlipped=new Set();memoryMatched=new Set();memoryOpen=[];memoryRevealed=false;memoryAttempts=0;$('memoryAward').innerHTML='';$('memoryHeading').textContent=festivals[memoryFestival].name+' · 圖片與文字配對';$('memoryQuestion').hidden=true;$('memoryListen').hidden=true;$('memoryNext').hidden=true;$('memoryFeedback').textContent='逐張點擊翻牌：已翻開 0 / 6。全部翻開後，再選圖片與文字配對。';renderMemory();}
let memoryOpen=[];
function renderMemory(){$('memoryScore').textContent=memoryMatched.size+' 點 · 已配對 '+memoryMatched.size+' / 3';$('memoryAttempts').textContent='已配對 '+memoryAttempts+' 次 · 不限時間，不扣分';$('memoryBoard').innerHTML=memoryDeck.map((v,i)=>{const c=cards[v.id-1],done=memoryMatched.has(v.id),visible=memoryFlipped.has(i);return `<button class="memory-card revealed flip-card ${visible?'is-open':''} ${done&&visible?'matched':''} ${memoryOpen.includes(i)?'selected-pair':''}" data-memory="${i}" aria-label="${visible?(v.kind==='picture'?'圖片：':'文字：')+c.name:'第'+(i+1)+'張，未翻開'}" aria-pressed="${memoryOpen.includes(i)}" ${(done&&visible)||memoryWaiting||memoryShuffling?'disabled':''}><span class="flip-inner"><span class="flip-back" aria-hidden="true">？<small>點擊翻牌</small></span><span class="flip-front" aria-hidden="${!visible}">${v.kind==='picture'?art(c):'<span class="memory-word">'+c.name+'<small>'+c.en+'</small></span>'}<span class="memory-kind">${done?'✓ 已配對':v.kind==='picture'?'圖片':'文字'}</span></span></span></button>`;}).join('');}
$('memoryBoard').onclick=e=>{const b=e.target.closest('[data-memory]');if(!b||memoryWaiting||memoryShuffling)return;const i=+b.dataset.memory,v=memoryDeck[i];if(!memoryRevealed){if(memoryFlipped.has(i))return;memoryFlipped.add(i);b.classList.add('is-open');if(memoryMatched.has(v.id)){b.classList.add('matched');b.disabled=true;}b.querySelector('.flip-front').setAttribute('aria-hidden','false');b.setAttribute('aria-label',(v.kind==='picture'?'圖片：':'文字：')+cards[v.id-1].name);$('memoryFeedback').textContent='已翻開 '+memoryFlipped.size+' / 6。';if(memoryFlipped.size===6){memoryRevealed=true;$('memoryFeedback').textContent='六張都翻開了！選一張圖片，再選對應文字（也可以先選文字）。';}return;}if(memoryMatched.has(v.id))return;if(memoryOpen.includes(i)){memoryOpen=[];renderMemory();return;}memoryOpen.push(i);if(memoryOpen.length===1){$('memoryFeedback').textContent='已選一張，請找對應的'+(v.kind==='picture'?'文字':'圖片')+'。';renderMemory();return;}memoryAttempts++;const first=memoryDeck[memoryOpen[0]];if(first.id===v.id&&first.kind!==v.kind){memoryMatched.add(v.id);$('memoryFeedback').textContent='✓ 配對成功：'+cards[v.id-1].name+'，獲得1點！';$('memoryListen').hidden=false;$('memoryListen').onclick=()=>speak(cards[v.id-1]);if(memoryMatched.size<3){memoryWaiting=true;$('memoryNext').hidden=false;$('memoryFeedback').textContent+=' 按「蓋牌並洗牌」，再找下一組。';}if(memoryMatched.size===3){memoryBadges.add(memoryFestival);saveProgress();$('memoryAward').innerHTML=`<div class="completion-badge">${festivals[memoryFestival].name}<br><strong>翻牌記憶章</strong></div><p>三組配對完成！</p>`;}}else{$('memoryFeedback').textContent='這兩張不對應，請重新選一張圖片和對應文字。';}memoryOpen=[];renderMemory();};

$('memoryNext').onclick=()=>{if(!memoryWaiting||memoryShuffling)return;memoryShuffling=true;stopAudio();$('memoryNext').hidden=true;$('memoryListen').hidden=true;$('memoryFeedback').textContent='蓋牌、洗牌中……';document.querySelectorAll('[data-memory]').forEach(b=>{b.disabled=true;b.classList.remove('is-open','matched','selected-pair');});memoryShuffleTimer=setTimeout(()=>{const previous=memoryDeck;memoryDeck=shuffle(previous);if(memoryDeck.every((v,i)=>v===previous[i]))memoryDeck.push(memoryDeck.shift());memoryFlipped=new Set();memoryOpen=[];memoryRevealed=false;memoryWaiting=false;memoryShuffling=false;renderMemory();$('memoryFeedback').textContent='已重新洗牌！逐張翻開六張牌，再找尚未得分的一組。已收集的組合不重複加分。';},700);};
